blank_issues_enabled: false
  contact_links:                                                                                                      
     - name: Slack — GiveWell colleagues
       url: https://givewell.slack.com/team/U0AEMGX922D
       about: Message Ally Rome on Slack for quick questions
     - name: Email
       url: mailto:ally.rome@givewell.org
       about: For external collaborators or non-Slack questions
